### ISSUE TITLE
Any view controller with text field should have the keyboard ready (Broker login controllers)

### ISSUE THREAD

**Issue by imougy** [tradingticket/TradeItIosTicketSDKLib#21] opened 2015-08-05 21:40 UTC
To speed up user taps.
![image](https://cloud.githubusercontent.com/assets/3361440/9098636/eb030ad8-3b7f-11e5-993b-f1d66e4c9c9d.png)

**Comment by acegreen** [comment] 2015-12-23 17:06
I see thats already implemented. Just an additional comment:

on iPad (landscape mode) the view scrolls up (unnecessary) because the keyboard doesn't obscure the textfield in edit mode. The issue is when you dismiss the keyboard, the view is stuck scrolled up. 

I think the current implementation is a custom one. I would suggest letting a UITableViewController handle that. It does the necessary scrolling by default.

**Comment by TheAntonioReyes** [comment] 2015-12-28 18:29
We'll track ipad issues in a separate issue. I'll close this as it's now complete.

@acegreen this is a standard UITableViewController, I'm not sure what could be causing that. I'll add this into the iPad issues since there is not a keyboard dismissal button on the phone.

**Closed by TheAntonioReyes** 2015-12-28 18:29 UTC
Labels: in progress

**Comment by acegreen** [comment] 2015-12-28 18:40
Issue seems to also affect iPhone. I was on simulator and was NOT using the soft keyboard, yet the view moved up and the black space appeared. 

![simulator screen shot dec 28 2015 12 59 21 pm](https://cloud.githubusercontent.com/assets/10794609/12023532/6d31cf58-ad68-11e5-93fa-c213a6b59097.png)
